FROM rchain/buildenv:latest
ARG REPO_URL=https://github.com/rchain/rchain
ARG REPO_REF=dev
WORKDIR tmpclone
RUN git init && git fetch --depth 1 $REPO_URL $REPO_REF && git checkout FETCH_HEAD
# First `sbt update` says "Copying runtime jar." and exits.
RUN sbt update
RUN sbt update
WORKDIR ..
RUN rm -rf tmpclone
