#!/bin/bash
set -ev -o pipefail

BASE_PACKAGES=(
	apt-transport-https
	ca-certificates
	curl
	gnupg
	lsb-release
)
apt update
apt install -y --no-install-recommends ${BASE_PACKAGES[@]}

apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
echo 'deb https://dl.bintray.com/sbt/debian /' >/etc/apt/sources.list.d/sbt.list

echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" >/etc/apt/sources.list.d/docker-ce.list
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

apt update

PACKAGES=(
	locales

	# build dependencies
	java-common
	jflex
	openjdk-11-jdk-headless
	openjdk-8-jdk-headless
	sbt=1.\*

	# integration tests
	python3
	python3-pip

	# packaging
	docker-ce
	rpm
	fakeroot
	lintian
)
apt install -y --no-install-recommends ${PACKAGES[@]}

apt clean

sed -i 's/^# *\(en_US.UTF-8\)/\1/' /etc/locale.gen
locale-gen

# p2p-test-tool.py
pip3 install argparse docker pexpect requests
# integration-testing/
pip3 install docker pytest delayed_assert

curl -s https://codecov.io/bash >/usr/local/bin/codecov
chmod +x /usr/local/bin/codecov
