#!/bin/bash
set -e

N=rchain/buildenv
git fetch -t
V=$(git describe --tags)

set -x
docker build -t $N:$V .
docker tag $N:$V $N:latest

set +x
builtin echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

set -x
docker push $N:$V
docker push $N:latest
