#!/bin/bash
set -e

N=rchain/buildenv
C=${DRONE_COMMIT_SHA:-$(git rev-parse --short HEAD)}
git fetch -t
V=$(git describe --tags)

set -x
docker build -t $N:$C .
docker tag $N:$C $N:$V
docker tag $N:$C $N:latest
set +x

builtin echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

set -x
docker push $N:$V
docker push $N:latest
set +x
